global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "signaldesk"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "innocent-elinore-josephkim-suzuki-1e11ded2.koyeb.app"